### ISSUE TITLE
Landing page search box does not work until you select a version

### ISSUE THREAD

**Issue by germa89** [ansys/ansys-sphinx-theme#571] opened 2024-10-29 09:34 UTC
### 🔍 Before submitting the issue

- [x] I have searched among the existing issues
- [x] I am using a Python virtual environment

### 🐞 Description of the bug

Reported by Pablo Vargas:

> Hi Germán, good morning. I would like to inform you that the pymapdl search engine does not return any results on the landing page
https://mapdl.docs.pyansys.com/ , however, it works correctly when used after selecting a version, in this case the stable version...
https://mapdl.docs.pyansys.com/version/stable/index.html 

I guess the search feature is linked to `version/something` but not to just `mapdl.docs.pyansys.com`.

### 📝 Steps to reproduce

NA

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

NA

### 🐍 Which Python version are you using?

3.9

### 📦 Installed packages

https://github.com/ansys/pymapdl/blob/main/pyproject.toml

**Comment by RobPasMue** [comment] 2024-10-29 09:40
Good catch - we need to fix this @Revathyvenugopal162 @jorgepiloto

**Comment by jorgepiloto** [comment] 2024-10-29 11:12
This is a consequence of a breaking change we added in both the actions and the theme. Best way to fix this is to update the landing page `index.html` directly in `gh-pages` branch. So far, I can see this failing for:

- PyAnsys Geoemtry
- PyMAPDL

**Comment by Revathyvenugopal162** [comment] 2024-10-29 11:15
The issue comes from recent changes implemented in our theme. A patch release with the latest theme in the libraries should resolve these issues.

**Comment by jorgepiloto** [comment] 2024-10-30 09:41
The issue is fixed. However, it would be great if you could perform a patch release in PyMAPDL and PyAnsys Geometry, @germa89 @RobPasMue.

The reason is that "ansys-sphinx-theme==v1.1.7" improves the performance of the search. We are planning to release v1.2 today. This better indexes the API section and allows users to exclude dirs and files from being indexed.

Closing this since it is no longer an issue on the theme.

**Closed by jorgepiloto** 2024-10-30 09:41 UTC
Labels: bug

**Comment by germa89** [comment] 2024-10-30 17:14
I will do a patch release after Lyon. :)
