### ISSUE TITLE
Horizontal scroll bar is not available

### ISSUE THREAD

**Issue by MaxJPRey** [ansys/ansys-sphinx-theme#205] opened 2023-02-21 21:26 UTC
The horizontal scroll bar is not available unless you scroll down to the bottom.
To reproduce the issue, you can open this [link](https://aedt.docs.pyansys.com/dev/API/_autosummary/pyaedt.modeler.modeler3d.Modeler3D.html).

If you scroll down, you will see the horizontal scroll bar showing up again.
![image](https://user-images.githubusercontent.com/87315832/220461393-ac6043d9-f5a1-4336-87d7-d9273a955631.png)

With the new collapse navigation, we might not need this horizontal scroll bar as much as we used to.
This might already be fixed. In that case, feel free to close it.

**Comment by jorgepiloto** [comment] 2024-10-15 08:42
Looks like this is no longer showing, @MaxJPRey:

https://aedt.docs.pyansys.com/version/stable/API/_autosummary/ansys.aedt.core.modeler.modeler_3d.Modeler3D.html#ansys.aedt.core.modeler.modeler_3d.Modeler3D

The bar is showing both in Firefox 131.0.2 (64-bit) and Edge Version 129.0.2792.89

**Comment by jorgepiloto** [comment] 2024-10-15 08:42
If the issue is no longer present, feel free to close the issue.

**Closed** 2024-10-15 08:44 UTC
